name: Create and publish a Docker image

on:
  push:
    tags:
      - 'v*'
env:
  REGISTRY: ghcr.io
  REPOSITORY: ghcr.io/${{ github.repository_owner }} 

jobs:
  build-and-push-receiver:
    name: "Build irc-eew"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      
      - name: Build and push
        uses: ./.github/actions/build
        with:
          context: .
          artifact: irc-eew
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-push-eewview:
    name: "Build EEW Viewer"
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and push
        uses: ./.github/actions/build
        with:
          context: ./HTML/
          artifact: eew-view
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
